export const documentTypes = [
  { label: "Cedula de ciudadanía", value: "CC" },
  { label: "Cedula de ciudadanía de primera vez", value: "CC PV" },
  { label: "Duplicado de cédula de ciudadanía", value: "CC DUP" },
  { label: "Renovación de cédula de ciudadanía", value: "CC REN" },
  { label: "Rectificación de cedula de ciudadanía", value: "CC REC" },
  { label: "Cédula digital", value: "CC DIG" },
  { label: "Centro de consulta técnica", value: "CCT" },
  { label: "Unidad de captura de datos en papel", value: "DCU" },
  { label: "Estación integrada de servicios", value: "EIS" },
  {
    label: "Herramienta Logística de Entrega de documentos vía web",
    value: "HLED-WEB",
  },
  { label: "Manejador de Transacciones", value: "MTR" },
  { label: "Número de Identificación personal", value: "NIP" },
  { label: "Número Único de Identificación Personal", value: "NUIP" },
  { label: "Sistema de Información de Correspondencia", value: "SIC" },
  {
    label: "Sistema Integral de tramites al ciudadano (Cancillería)",
    value: "SITAC",
  },
  { label: "Tarjeta de identidad", value: "TI" },
  { label: "Tarjeta de identidad de primera vez", value: "TI PV" },
  { label: "Duplicado de tarjeta de identidad", value: "TI DUP" },
  { label: "Renovación de tarjeta de identidad", value: "TI REN" },
  { label: "Rectificación de tarjeta de identidad", value: "TI REC" },
];
